apiVersion: apps/v1
kind: Deployment
metadata:
  name: starling-ui
spec:
  selector:
    matchLabels:
      app: starling-ui
  template:
    metadata:
      labels:
        app: starling-ui
    spec:
      shareProcessNamespace: true
      containers:
      - name: starling-ui
        image: uobflightlabstarling/starling-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: starling-ui-srv
spec:
  type: LoadBalancer
  selector:
    app: starling-ui 
  ports:
    - port: 3000
      name: http
    - port: 9090
      name: ros-bridge
    