apiVersion: apps/v1
kind: Deployment
metadata:
  name: starling-ui
spec:
  selector:
    matchLabels:
      app: starling-ui
  template:
    metadata:
      labels:
        app: starling-ui
    spec:
      shareProcessNamespace: true
      containers:
      - name: starling-ui
        image: uobflightlabstarling/starling-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: starling-ui-srv
spec:
  type: NodePort
  selector:
    app: starling-ui 
  ports:
    - port: 3000
      nodePort: 30000
      name: http
    - port: 9090
      targetPort: 9090
      nodePort: 30001
      name: ros-bridge
    