apiVersion: apps/v1
kind: Deployment
metadata:
  name: starling-sitl
  labels:
    app: starling-sitl
spec:
  selector: 
    matchLabels:
      app: starling-sitl
  template:
    metadata:
      labels:
        app: starling-sitl
    spec:
      containers:
      - name: starling-sitl
        image: starling-ardupilot-sitl:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SYSID
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 14553
          protocol: "UDP"
        - containerPort: 5760
        - containerPort: 5762
        - containerPort: 5763
      - name: starling-mavros
        image: starling-mavros:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MAVROS_FCU_URL
          value: tcp://127.0.0.1:5762
        - name: MAVROS_TGT_SYSTEM
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 5762
      - name: network-tools
        image: praqma/network-multitool
  