version: '3'

services:
  simhost: # Must be called simhost
    image: uobflightlabstarling/starling-sim-rover:latest
    environment:
      - "PX4_SIM_HOST=localhost"
    network_mode: host

  sitl:
    image: uobflightlabstarling/starling-sim-px4-sitl:latest
    environment:
      - "PX4_SIM_HOST=localhost"
      - "PX4_OFFBOARD_HOST=localhost"
    network_mode: host
    depends_on: 
      - simhost

  # mavros:
  #   image: uobflightlabstarling/starling-mavros:latest
  #   command: ros2 launch launch/mavros_bridge.launch.xml
  #   environment:
  #     - "MAVROS_TGT_SYSTEM=1"
  #     - "MAVROS_FCU_IP=0.0.0.0"
  #   network_mode: host
  #   depends_on:
  #     - sitl
