version: '3'

services:
  sitl:
    image: uobflightlabstarling/starling-sim-arducopter:latest
  
  mavros:
    image: uobflightlabstarling/starling-mavros:latest
    command: ros2 launch launch/mavros_bridge.launch.xml
    environment: 
      - "MAVROS_FCU_URL=tcp://sitl:5760"

  ui: 
    image: uobflightlabstarling/starling-ui:latest
    ports:
      - "3000:3000"
      - "9090:9090"