site_name: Project Starling
theme: readthedocs
repo_url: https://github.com/UoBFlightLab/ProjectStarling
site_description: 'BRL Flight Arena 2.0'
docs_dir: 'docs'
copyright: Copyright &copy; 2021 University of Bristol Flight Laboratory

markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.keys:
      strict: True

plugins:
  - search
  - macros
  - enumerate-headings:
      toc_depth: 3
  - mermaid2

extra_css: [ kbd.css ]

nav:
  - "Home":
    - "Overview": 'README.md'
    - "Getting Started": 'guide/getting-started.md'
    - "Background": 'details/background.md'
    - "Ecosystem": 'other/related_projects_and_links.md'
  - "Tutorials":
    - "Introduction to Starling": 'tutorials/introduction.md'
  - "Single Drone User Guides":
    - "Single Drone Simulation on Local Machine": "guide/single-drone-local-machine.md"
    - "Single Drone Simulation on Local Cluster": "guide/kube-single-drone-local-machine.md"
    - "Single Drone on Hardware": "guide/single-drone-drones.md"
    - "Windows Support": "guide/windows-support.md"
  - "Multiple Drone User Guides":
    - "Multiple Drones Simulation on Local Cluster": "guide/multiple-drone-local-machine.md"
    - "Multiple Drones on Hardware": "guide/multiple-drone-drones.md"
  - "Additional Guides":
    - "Developing a controller": 'guide/writing-a-controller.md'
    - "Development Guide": 'guide/development.md'
    - "Understanding Docker": 'details/docker.md'
    - "Understanding Kubernetes": "details/kubernetes.md"
    - "Kubernetes Dashboard Guide": 'details/kubernetes-dashboard.md'
  - "Physical Flight":
    - "BRL Flight Arena": "details/flight_arena.md"
    - "Adding A New Vehicle" : "details/adding_physical_drone.md"
  - "Implementation":
    - "Example Python Controller": "guide/example-controller.md"
    - "Example Kubernetes Deployments": "details/kubernetes-deployment.md"
    - "Build System": "details/build_system.md"
  - "Image Documentation":
    - "starling-ui": "docker-images/ui.md"
    - "starling-mavros": "docker-images/mavros.md"
    - "starling-sim-base-core": "docker-images/sim-base-core.md"
    - "starling-sim-ardupilot-copter/plane": "docker-images/sim-ardupilot-vehicle.md"
    - "starling-sim-ardupilot-gazebo": "docker-images/sim-ardupilot-gazebo.md"
    - "starling-sim-iris-ap": "docker-images/sim-iris-ap.md"
  - "Miscellaneous":
    - "Ideas": "other/ideas.md"
    - "MATLAB (unstable)": "other/MATLAB.md"
