apiVersion: v1
kind: Pod
metadata:
  name: demo-listener
spec:
  # hostNetwork: true
  containers:
  - name: ros-listener
    image: ros_demo
    imagePullPolicy: IfNotPresent
    # ports:
    # - containerPort: 5762
    args: ["ros2", "run", "demo_nodes_py", "listener"]
  - name: network-toolbox
    image: praqma/network-multitool
  