mavros:
  ros__parameters:
    component_id: 191
    plugin_denylist:
      - "*"
    plugin_allowlist:
      # - altitude
      - command
      - distance_sensor
      # - ftp
      # - global_position
      # - imu
      - local_position
      # - manual_control
      # - param
      # - px4flow
      # - rc_io
      # - setpoint_accel
      # - setpoint_attitude
      - setpoint_position
      # - setpoint_raw
      # - setpoint_velocity
      - sys_status
      - sys_time
      - vision_pose
      - log_transfer
      # - onboard_computer_status
      # - vibration

# Old format

# plugin_blacklist:
# # common
# - actuator_control
# - ftp
# - safety_area
# - hil
# # extras
# - altitude
# - debug_value
# - image_pub
# - px4flow
# - vibration
# - vision_speed_estimate
# - wheel_odometry

# plugin_whitelist: []
# #- 'sys_*