# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gzweb
#   labels: 
#     app: gzweb
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 8080
#     name: http
#   selector:
#     app: gazebo

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: gazebo-srv
#   labels:
#     app: gazebo
# spec:
#   clusterIP: None
#   ports:
#   - port: 8080
#     name: http
#   - port: 11345
#     name: tcp
#   - port: 7400
#     name: dds1
#     protocol: UDP
#   - port: 7401
#     name: dds2
#     protocol: UDP
#   - port: 7410
#     name: dds3
#     protocol: UDP
#   - port: 7411
#     name: dds4
#     protocol: UDP
#   - port: 7412
#     name: dds5
#     protocol: UDP
#   - port: 7413
#     name: dds6
#     protocol: UDP
#   - port: 7414
#     name: dds7
#     protocol: UDP
#   - port: 7415
#     name: dds8
#     protocol: UDP
#   - port: 7418
#     name: dds9
#     protocol: UDP
#   - port: 7419
#     name: dds10
#     protocol: UDP
#   - port: 7422
#     name: dds11
#     protocol: UDP
#   - port: 7423
#     name: dds12
#     protocol: UDP
#   - port: 10318
#     name: dds13
#     protocol: UDP
#   - port: 10317
#     name: dds14
#     protocol: UDP
#   selector:
#     app: gazebo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gazebo-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gazebo
  template:
    metadata:
      labels:
        app: gazebo
        version: v1
    spec:
      # hostname: sim-gazebo
      # subdomain: gazebo-srv
      hostNetwork: true
      shareProcessNamespace: true
      nodeSelector:
          beta.kubernetes.io/arch: "amd64"
      containers:
      - name: gazebo
        image: uobflightlabstarling/starling-sim-iris:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        args: [ "ros2", "launch", "launch/iris.launch.xml" , sim_only:=true]
        ports:
        - containerPort: 8080
        - containerPort: 7681
        - containerPort: 11345
        - containerPort: 4560
        - containerPort: 7400
          protocol: UDP
        - containerPort: 7401
          protocol: UDP
        - containerPort: 7410
          protocol: UDP
        - containerPort: 7411
          protocol: UDP
        - containerPort: 7412
          protocol: UDP
        - containerPort: 7413
          protocol: UDP
        - containerPort: 7414
          protocol: UDP
        - containerPort: 7415
          protocol: UDP
        - containerPort: 7418
          protocol: UDP
        - containerPort: 7419
          protocol: UDP
        - containerPort: 7422
          protocol: UDP
        - containerPort: 7423
          protocol: UDP
        - containerPort: 10318
          protocol: UDP
        - containerPort: 10317
          protocol: UDP
 