apiVersion: apps/v1
kind: Deployment
metadata:
  name: gazebo-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gazebo
  template:
    metadata:
      labels:
        app: gazebo
        version: v1
    spec:
      # hostname: sim-gazebo
      # subdomain: gazebo-srv
      hostNetwork: true
      shareProcessNamespace: true
      nodeSelector:
          beta.kubernetes.io/arch: "amd64"
      containers:
      - name: gazebo
        image: uobflightlabstarling/starling-sim-iris:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        args: [ "ros2", "launch", "launch/iris.launch.xml" , sim_only:=true]
        ports:
        - containerPort: 8080
        - containerPort: 7681
        - containerPort: 11345
        - containerPort: 4560
        - containerPort: 7400
          protocol: UDP
        - containerPort: 7401
          protocol: UDP
        - containerPort: 7410
          protocol: UDP
        - containerPort: 7411
          protocol: UDP
        - containerPort: 7412
          protocol: UDP
        - containerPort: 7413
          protocol: UDP
        - containerPort: 7414
          protocol: UDP
        - containerPort: 7415
          protocol: UDP
        - containerPort: 7418
          protocol: UDP
        - containerPort: 7419
          protocol: UDP
        - containerPort: 7422
          protocol: UDP
        - containerPort: 7423
          protocol: UDP
        - containerPort: 10318
          protocol: UDP
        - containerPort: 10317
          protocol: UDP
