#!/bin/bash

# If MAVROS_TGT_SYSTEM is zero, then set instance id to take MAVROS_TGT_SYSTEM_BASE + ORDINAL-1 from StatefulSet hostname
# Hostname is of the form '<stateful set name>-<ordinal>'
if [ "$MAVROS_TGT_SYSTEM" -eq "0" ]; then
    if [ -f "/etc/drone.config" ]; then 
        echo "MAVROS_TGT_SYSTEM will be read from file not yet implemented, set to 1 for now"
        MAVROS_TGT_SYSTEM=1
    else
        ORDINAL="${HOSTNAME##*-}"
        MAVROS_TGT_SYSTEM=$((MAVROS_TGT_SYSTEM_BASE + ORDINAL));
        echo "MAVROS_TGT_SYSTEM set to $MAVROS_TGT_SYSTEM (from hostname: $HOSTNAME), was set to zero and /etc/drone.config not found"
    fi
else
    echo "MAVROS_TGT_SYSTEM setting as specified: $MAVROS_TGT_SYSTEM"
fi

export MAVROS_TGT_SYSTEM=$MAVROS_TGT_SYSTEM


if [ ! -v $VEHICLE_NAMESPACE ]; then
    # If set Ensure VEHICLE_NAMESPACE is a valid topic name
    # Replace all '-' with '_'
    export VEHICLE_NAMESPACE=${VEHICLE_NAMESPACE//-/_}
    echo "VEHICLE_NAMESPACE setting to $VEHICLE_NAMESPACE"
else
    echo "VEHICLE_NAMESPACE not set, default to mavros_bridge.launch.xml default"
fi


if [ -v $MAVROS_FCU_URL ]; then
    # If not set, then autogenerate based on subparameters and the target system id dynamically
    export MAVROS_FCU_URL="$MAVROS_FCU_CONN://$MAVROS_FCU_IP:$((MAVROS_FCU_UDP_BASE + MAVROS_TGT_SYSTEM))@"
    echo "MAVROS_FCU_URL not set, defaulting to autogenerated: $MAVROS_FCU_URL"
else
    echo "MAVROS_FCU_URL setting to $MAVROS_FCU_URL"
fi