mavros/altitude:
  ros__parameters:
    frame_id: map
    use_sim_time: false

mavros/cmd:
  ros__parameters:
    command_ack_timeout: 5.0
    use_comp_id_system_control: false
    use_sim_time: false

mavros/imu:
  ros__parameters:
      frame_id: "base_link"
      # need find actual values
      linear_acceleration_stdev: 0.0003
      angular_velocity_stdev: 0.0003490659 
      orientation_stdev: 1.0
      magnetic_stdev: 0.0

mavros/global_position:
  ros__parameters:
    child_frame_id: base_link
    frame_id: map
    gps_uere: 1.0
    rot_covariance: 99999.0
    tf:
      child_frame_id: base_link
      frame_id: map
      global_frame_id: earth
      send: false
    use_relative_alt: true
    use_sim_time: false

mavros/local_position:
  ros__parameters:
    frame_id: map
    tf:
      child_frame_id: base_link
      frame_id: map
      send: false
    use_sim_time: false

mavros/setpoint_attitude:
  ros__parameters:
    reverse_thrust: false
    use_quaternion: false
    use_sim_time: false

mavros/setpoint_position:
  ros__parameters:
    mav_frame: LOCAL_NED
    use_sim_time: false

mavros/setpoint_raw:
  ros__parameters:
    thrust_scaling: 1.0
    use_sim_time: false

mavros/setpoint_velocity:
  ros__parameters:
    mav_frame: LOCAL_NED
    use_sim_time: false

mavros/setpoint_accel:
  ros__parameters:
    send_force: false
    use_sim_time: false

mavros/distance_sensor:
  ros__parameters:
    base_frame_id: base_link
    config: "{rangefinder: {
                subscriber: true, 
                id: 0, 
                frame_id: rangefinder, 
                orientation: PITCH_270, 
                horizontal_fov_ratio: 0.5, 
                vertical_fov_ratio: 0.5}
              }"
    use_sim_time: false


mavros/vision_pose:
  ros__parameters:
    tf/child_frame_id: vision_estimate
    tf/frame_id: map
    tf/listen: false
    tf/rate_limit: 10.0
    use_sim_time: false

mavros/vibration:
  ros__parameters:
    frame_id: base_link
    use_sim_time: false
