mavros:
  ros__parameters:
    component_id: 191
    plugin_denylist:
      - "*"
    plugin_allowlist: 
      - 'sys_*'
      - altitude
      - command
      - distance_sensor
      # - ftp
      - global_position
      - imu
      - local_position
      - manual_control
      # - param
      - px4flow
      # - rc_io
      - setpoint_accel
      - setpoint_attitude
      - setpoint_position
      - setpoint_raw
      - setpoint_velocity
      - sys_status
      - sys_time
      - vision_pose_estimate
      # - vision_speed_estimate
      # - waypoint
    
