---
apiVersion: v1
kind: Pod
metadata:
  name: debug-multitalker-laptop
spec:
  hostNetwork: true
  shareProcessNamespace: true
  containers:
  - name: ros-talker1
    image: uobflightlabstarling/ros_debug
    imagePullPolicy: Always
  - name: ros-talker2
    image: uobflightlabstarling/ros_debug
    imagePullPolicy: Always
  - name: network-toolbox
    image: praqma/network-multitool
  nodeSelector:
    kubernetes.io/arch: amd64
    # k3s.io/hostname: clover1
  
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-multitalker-clover1
spec:
  hostNetwork: true
  shareProcessNamespace: true
  containers:
  - name: ros-talker1
    image: uobflightlabstarling/ros_debug
    imagePullPolicy: Always
  - name: ros-talker2
    image: uobflightlabstarling/ros_debug
    imagePullPolicy: Always
  - name: network-toolbox
    image: praqma/network-multitool
  nodeSelector:
    # kubernetes.io/arch: arm64
    k3s.io/hostname: clover1

---
apiVersion: v1
kind: Pod
metadata:
  name: debug-multitalker-raspi1
spec:
  hostNetwork: true
  shareProcessNamespace: true
  containers:
  - name: ros-talker1
    image: uobflightlabstarling/ros_debug
    imagePullPolicy: Always
  - name: ros-talker2
    image: uobflightlabstarling/ros_debug
    imagePullPolicy: Always
  - name: network-toolbox
    image: praqma/network-multitool
  nodeSelector:
    # kubernetes.io/arch: arm64
    k3s.io/hostname: raspi1