FROM ros:foxy-ros-base-focal

# Build v 1.0.7 rosbridge
RUN git clone -b 1.0.7 https://github.com/RobotWebTools/rosbridge_suite.git /ros_ws/src/rosbridge_suite

# Install rosbridge suite and associated messages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        ros-foxy-mavros-msgs \
        ros-foxy-gazebo-msgs \
    && rosdep install --from-paths /ros_ws/src -y\
    && rm -rf /var/lib/apt/lists/*

RUN . /opt/ros/${ROS_DISTRO}/setup.sh \
    && cd /ros_ws \
    && export CMAKE_PREFIX_PATH=$AMENT_PREFIX_PATH:$CMAKE_PREFIX_PATH \
    && colcon build --cmake-force-configure \
    && rm -r build

# Add custom ROS DDS configuration (force UDP always)
COPY fastrtps_profiles.xml /ros_ws/
ENV FASTRTPS_DEFAULT_PROFILES_FILE /ros_ws/fastrtps_profiles.xml

COPY rosbridge_websocket_launch.xml /ros_ws/
COPY ros_entrypoint.sh /
COPY run.sh /

ENV ROSBRIDGE_PORT 9090
ENV MSGS_WS "/msgs_ws"

# Expose websocket server
EXPOSE ${ROSBRIDGE_PORT}

# Set initial command
CMD ["./run.sh"]