name: 'Update images'

on:
  # Triggers on push to any tag of form v* or latest
  push:
    tags:
      - 'v*'
      - 'latest'

jobs:
  bake_system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (system)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            system
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}

      - name: Build and push (example_python_controller)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            example_python_controller
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}

  bake_simulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (base-core)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            simulator
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}

      - name: Build and push (PX4)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            simulator-px4
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}

      - name: Build and push (Iris)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            starling-sim-iris
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
