name: 'Update dev images'

on:
  # Triggers on push to any tag of form vX.X.X-dev
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev'

jobs:
  bake_controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (controller-base)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            starling-controller-base
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
          NAMEDTAG: nightly

      - name: Build and push (example_python_controller)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            example_python_controller
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
          NAMEDTAG: nightly

  bake_simulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (base-core)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            simulator
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
          NAMEDTAG: nightly

      - name: Build and push (PX4)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            simulator-px4
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
          NAMEDTAG: nightly

      - name: Build and push (Iris)
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            starling-sim-iris
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
          NAMEDTAG: nightly

  bake_ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            starling-ui
          push: true
        env:
          VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
          NAMEDTAG: nightly

  bake_mavros:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: system/mavros
          tags: |
            uobflightlabstarling/starling-mavros:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-mavros:nightly
          push: true
          cache-from: uobflightlabstarling/starling-mavros:cache-dev
          cache-to: uobflightlabstarling/starling-mavros:cache-dev
          platforms: linux/amd64,linux/arm64
