name: 'Update images'

on:
  # Triggers on push to any tag of form v*
  push:
    tags:
      - 'v*'

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          files: |
            ./buildtools/docker-bake.hcl
          targets: |
            default
          push: true
        env:
          TAG: ${{ steps.tag_name.outputs.GITHUB_TAG }}
