name: 'Update dev images'

on:
  # Triggers on push to any tag of form vX.X.X-dev
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev'

jobs:
  build_controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (controller-base)
        uses: docker/build-push-action@v2
        with:
          context: system/controller-base
          tags: |
            uobflightlabstarling/starling-controller-base:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-controller-base:nightly
          push: true
          cache-from: uobflightlabstarling/starling-controller-base:cache-dev
          cache-to: uobflightlabstarling/starling-controller-base:cache-dev
          platforms: linux/amd64,linux/arm64

      - name: Build and push (example_controller_python)
        uses: docker/build-push-action@v2
        with:
          context: controllers/example_controller_python
          build-args:
            VERSION=${{ steps.tag_name.outputs.GITHUB_TAG }}
          tags: |
            uobflightlabstarling/example_controller_python:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/example_controller_python:nightly
          push: true
          cache-from: uobflightlabstarling/example_controller_python:cache-dev
          cache-to: uobflightlabstarling/example_controller_python:cache-dev
          platforms: linux/amd64,linux/arm64


  build_simulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (sim-base-core)
        uses: docker/build-push-action@v2
        with:
          context: simulator/base/core
          tags: |
            uobflightlabstarling/starling-sim-base-core:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-sim-base-core:nightly
          push: true
          cache-from: uobflightlabstarling/starling-sim-base-core:cache-dev
          cache-to: uobflightlabstarling/starling-sim-base-core:cache-dev
          platforms: linux/amd64
      
      - name: Build and push (sim-base-px4)
        uses: docker/build-push-action@v2
        with:
          context: simulator/base/px4
          build-args:
            VERSION=${{ steps.tag_name.outputs.GITHUB_TAG }}
          tags: |
            uobflightlabstarling/starling-sim-base-px4:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-sim-base-px4:nightly
          push: true
          cache-from: uobflightlabstarling/starling-sim-base-px4:cache-dev
          cache-to: uobflightlabstarling/starling-sim-base-px4:cache-dev
          platforms: linux/amd64

      - name: Build and push (sim-iris)
        uses: docker/build-push-action@v2
        with:
          context: simulator/vehicles/iris
          build-args:
            VERSION=${{ steps.tag_name.outputs.GITHUB_TAG }}
          tags: |
            uobflightlabstarling/starling-sim-iris:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-sim-iris:nightly
          push: true
          cache-from: uobflightlabstarling/starling-sim-iris:cache-dev
          cache-to: uobflightlabstarling/starling-sim-iris:cache-dev
          platforms: linux/amd64


  build_sitl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (px4-sitl)
        uses: docker/build-push-action@v2
        with:
          context: simulator/base/px4
          file: simulator/base/px4/sitl.Dockerfile
          tags: |
            uobflightlabstarling/starling-sim-px4-sitl:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-sim-px4-sitl:nightly
          push: true
          cache-from: uobflightlabstarling/starling-sim-px4-sitl:cache-dev
          cache-to: uobflightlabstarling/starling-sim-px4-sitl:cache-dev
          platforms: linux/amd64


  build_ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: system/ui
          tags: |
            uobflightlabstarling/starling-ui:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-ui:nightly
          push: true
          cache-from: uobflightlabstarling/starling-ui:cache-dev
          cache-to: uobflightlabstarling/starling-ui:cache-dev
          platforms: linux/amd64,linux/arm64


  build_mavros:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: system/mavros
          tags: |
            uobflightlabstarling/starling-mavros:${{ steps.tag_name.outputs.GITHUB_TAG }}
            uobflightlabstarling/starling-mavros:nightly
          push: true
          cache-from: uobflightlabstarling/starling-mavros:cache-dev
          cache-to: uobflightlabstarling/starling-mavros:cache-dev
          platforms: linux/amd64,linux/arm64
